# Generated by Django 5.0.4 on 2024-10-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_abbr', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('grade', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='apis.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='apis.classroom')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='apis.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('classroom', models.ManyToManyField(related_name='teachers', to='apis.classroom')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='apis.school')),
            ],
        ),
    ]
